# 1. Relational Operators

## 1.1 Equality

The most basic form of comparison is equality.

In [4]:
# Comparison of logicals
TRUE == FALSE

# Comparison of numerics
-6*14 != 17-101

# Comparison of character strings
'useR' == 'user'

# Compare a logical with a numeric
TRUE == 1

[1] FALSE

[1] FALSE

[1] FALSE

[1] TRUE

Since `TRUE` coerces to `1` under the hood, `TRUE` == `1` evaluates to `TRUE`. 
>Make sure not to mix up `==` ***(comparison)*** and `=` ***(assignment)***, `==` is what need to check the equality of R objects

## 1.2 Greater and less than

Apart from equality operators, Filip also introduced the less than and greater than operators: `<` and `>`. You can also add an equal sign to express *less than or equal to* or *greater than or equal to*, respectively.

> Remember that for string comparison, R determines the greater than relationship based on alphabetical order. Also, keep in mind that `TRUE` is treated as `1` for arithmetic, and `FALSE` is treated as `0`. Therefore, `FALSE` `<` `TRUE` is `TRUE`.

In [2]:
# Comparison of numerics
-6 * 5 + 2 >= -10+1

# Comparison of character strings
'raining'<='raining dogs'

# Comparison of logicals
TRUE > FALSE

[1] FALSE

[1] TRUE

[1] TRUE

## 1.3 Compare Vectors

R's relational operators also work on vectors.

In [3]:
linkedin <- c(16, 9, 13, 5, 2, 17, 14)
facebook <- c(17, 7, 5, 16, 8, 13, 14)

# Popular days
linkedin > 15

# Quiet days
linkedin <= 5

# LinkedIn more popular than Facebook
linkedin > facebook

[1]  TRUE FALSE FALSE FALSE FALSE  TRUE FALSE

[1] FALSE FALSE FALSE  TRUE  TRUE FALSE FALSE

[1] FALSE  TRUE  TRUE FALSE FALSE  TRUE FALSE

LinkedIn profile was pretty popular on the sixth day, but less so on the fourth and fifth day.

## 1.4 Compare Matrices



In [6]:
linkedin <- c(16, 9, 13, 5, 2, 17, 14)
facebook <- c(17, 7, 5, 16, 8, 13, 14)
views <- matrix(c(linkedin, facebook), nrow = 2, byrow = TRUE)

# When does views equal 13?
views == 13

# When is views less than or equal to 14?
views <= 14

[,1]  [,2]  [,3]  [,4]  [,5]  [,6]  [,7] 
[1,] FALSE FALSE  TRUE FALSE FALSE FALSE FALSE
[2,] FALSE FALSE FALSE FALSE FALSE  TRUE FALSE

[,1]  [,2] [,3] [,4]  [,5] [,6]  [,7]
[1,] FALSE TRUE TRUE  TRUE TRUE FALSE TRUE
[2,] FALSE TRUE TRUE FALSE TRUE  TRUE TRUE

# 2. Logical Operators

## 2.1. & and |

In [7]:
linkedin <- c(16, 9, 13, 5, 2, 17, 14)
last <- tail(linkedin, 1)

# Is last under 5 or above 10?
last < 5 | last >10

# Is last between 15 (exclusive) and 20 (inclusive)?
last >=15 & last <= 20

[1] TRUE

[1] FALSE

## 2.2. & and | (2)

Like relational operators, logical operators work perfectly fine with vectors and matrices.

In [8]:
# The social data (linkedin, facebook, views) has been created already

# linkedin exceeds 10 but facebook below 10
linkedin > 10 & facebook < 10

# When were one or both visited at least 12 times?
linkedin >= 12 | facebook >=12

# When is views between 11 (exclusive) and 14 (inclusive)?
views > 11 & views <=14

[1] FALSE FALSE  TRUE FALSE FALSE FALSE FALSE

[1]  TRUE FALSE  TRUE  TRUE FALSE  TRUE  TRUE

[,1]  [,2]  [,3]  [,4]  [,5]  [,6]  [,7]
[1,] FALSE FALSE  TRUE FALSE FALSE FALSE TRUE
[2,] FALSE FALSE FALSE FALSE FALSE  TRUE TRUE

The third day of the recordings was the only day where LinkedIn profile was visited more than 10 times, while Facebook profile wasn't. 

In [9]:
x <- 5
y <- 7
!(!(x < 4) & !!!(y > 12))

[1] FALSE

<div>
    <details>
    <summary>Blend it all together</summary>
    # li_df is pre-loaded in your workspace

    # Select the second column, named day2, from li_df: second
    second = li_df$day2

    # Build a logical vector, TRUE if value in second is extreme: extremes
    extremes = second > 25 | second <5

    # Count the number of TRUEs in extremes
    sum(extremes)
    </details>
</div>